Repository babysitter-finder/frontend, pull requests merged in 2020-08, with the labels that each got.

#3 Feature/webpack
  .babelrc
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/components/HelloWord.jsx
  src/index.js
  webpack.config.js
Labels: prework

#4 feature/eslint The eslint configurations was added
  .eslintrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/HelloWord.jsx
  src/index.js
  webpack.config.js
Labels: prework

#5 Feature/sass folder structure
  src/styles/animations/index.scss
  src/styles/components/atoms/atoms.txt
  src/styles/components/molecules/molecules.txt
  src/styles/components/organisms/organisms.txt
  src/styles/containers/containers.txt
  src/styles/layouts/layouts.txt
  src/styles/main.scss
  src/styles/variables.scss
Labels: prework

#8 feature/react-router React router was installed and implemented #7
  .eslintrc
  package-lock.json
  package.json
  src/index.js
  src/routes/App.js
Labels: prework

#10 Feature/variables
  src/styles/variables.scss
Labels: prework

#11 added basic animations
  src/styles/animations/index.scss
Labels: enhancement, help wanted

#12 feature/atoms The first component was build
  .eslintrc
  package-lock.json
  package.json
  src/components/HelloWord.jsx
  src/components/atoms/Button.jsx
  src/routes/App.js
  src/styles/components/atoms/Button.scss
  src/styles/components/atoms/atoms.txt
  src/styles/main.scss
  src/styles/variables.scss
Labels: enhancement

#13 Feature/stars
  .eslintrc
  src/assets/star.svg
  src/components/atoms/StarsRate.jsx
  src/components/atoms/StarsRating.jsx
  src/routes/App.js
  src/styles/components/atoms/Stars.scss
  src/styles/main.scss
Labels: enhancement

#14 feature/reset The resets were applied
  src/styles/main.scss
  src/styles/reset.scss
  src/styles/variables.scss
Labels: enhancement, prework

#15 feature/navbar The Header is ready to merge #9
  src/assets/girl.jpeg
  src/assets/logo.png
  src/assets/star.svg
  src/components/atoms/Logo.jsx
  src/components/molecules/Menu.jsx
  src/components/organisms/Header.jsx
  src/routes/App.js
  src/styles/components/molecules/Menu.scss
  src/styles/components/molecules/molecules.txt
  src/styles/components/organisms/Header.scss
  src/styles/components/organisms/organisms.txt
  src/styles/main.scss
Labels: enhancement

#16 feature/dialog-transparent The component is ready
  src/components/atoms/Button.jsx
  src/components/molecules/DialogTransparent.jsx
  src/routes/App.js
  src/styles/components/molecules/DialogTransparent.scss
  src/styles/main.scss
Labels: enhancement

#17 feature/popup-user-type The component is ready to merge
  src/components/molecules/PopupUserType.jsx
  src/routes/App.js
  src/styles/components/atoms/Button.scss
  src/styles/components/molecules/PopupUserType.scss
  src/styles/main.scss
Labels: enhancement

#19 feature/input The input was developed in the two modalities
  package-lock.json
  package.json
  src/components/molecules/Input.jsx
  src/routes/App.js
  src/styles/components/molecules/Input.scss
  src/styles/main.scss
Labels: enhancement

#21 feature/image-input The input upload image was made it
  src/components/molecules/ImageInput.jsx
  src/styles/components/molecules/ImageInput.scss
  src/styles/main.scss
  src/styles/variables.scss
  webpack.config.js
Labels: enhancement

#22 feature/range-input The range input was done #18
  src/components/molecules/RangeInput.jsx
  src/styles/components/molecules/RangeInput.scss
  src/styles/main.scss
Labels: enhancement

#23 feature/availability-input This commit has the component to check ava…
  src/components/molecules/AvailabilityInput.jsx
  src/routes/App.js
  src/styles/components/molecules/AvailabilityInput.scss
  src/styles/main.scss
Labels: enhancement

#24 feature/popup-delete-user The popup is ready to merge #18
  src/components/molecules/PopupDeleteUser.jsx
  src/routes/App.js
  src/styles/components/atoms/Button.scss
  src/styles/components/molecules/PopupDeleteUser.scss
  src/styles/components/molecules/PopupUserType.scss
  src/styles/main.scss
Labels: enhancement

#25 feature/caption The user caption is ready to merge #18
  src/components/molecules/Caption.jsx
  src/routes/App.js
  src/styles/components/molecules/Caption.scss
  src/styles/main.scss
Labels: enhancement

#26 feature/babysitter-mini-card The component was build #18
  src/components/atoms/StarsRate.jsx
  src/components/molecules/BabysitterMiniCard.jsx
  src/components/molecules/Caption.jsx
  src/styles/components/molecules/BabysitterMiniCard.scss
  src/styles/components/molecules/Caption.scss
  src/styles/components/molecules/ImageInput.scss
  src/styles/components/molecules/Menu.scss
  src/styles/main.scss
Labels: enhancement

#28 feature/login The login was integrated #27
  .babelrc
  package-lock.json
  package.json
  src/actions/usersActions.js
  src/components/atoms/Button.jsx
  src/components/molecules/Menu.jsx
  src/containers/Login.jsx
  src/index.js
  src/layouts/Layout.jsx
  src/reducers/index.js
  src/reducers/usersReducer.js
  src/routes/App.js
  src/styles/components/organisms/Header.scss
  src/styles/containers/Login.scss
  src/styles/containers/containers.txt
  src/styles/layouts/Layout.scss
  src/styles/layouts/layouts.txt
  src/styles/main.scss
  src/styles/variables.scss
  src/types/usersTypes.js
Labels: enhancement

#29 feature/signup The register form was implemented
  src/actions/usersActions.js
  src/components/molecules/ImageInput.jsx
  src/components/molecules/Menu.jsx
  src/containers/Email.jsx
  src/containers/Register.jsx
  src/reducers/usersReducer.js
  src/routes/App.js
  src/styles/components/molecules/ImageInput.scss
  src/styles/components/molecules/Input.scss
  src/styles/components/molecules/Select.scss
  src/styles/containers/Email.scss
  src/styles/containers/Register.scss
  src/styles/main.scss
  src/types/usersTypes.js
Labels: enhancement
